
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  timeout: 5000
  username: rvvergara
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: passionate_navigation_development
test:
  <<: *default
  database: passionate_navigation_test
production:
  <<: *default
  database: passionate_navigation_production
  username: passionate_navigation
  password: <%= ENV['PASSIONATE_NAVIGATION_DATABASE_PASSWORD'] %>
